### PR TITLE
Clipper.dbapi use

### PR DESCRIPTION
**Pull request by yama**
log.class.inc.php diff is last 2 lines.

### CODE REVIEW

**Comment by TimGS** [comment]
I can't merge this at the moment.
1. The commit c3e7ae3 should not be merged in case anyone is using the DELETE $fields FROM $table $where syntax
2. The other commits (but not c3e7ae3 curiously) are difficult to analyse. Anyone should be able to see what has changed but it's awkward because github shows everything has changed! We need to work out what is going on before accepting these commits. Incidentally I did look through 8d69213 and I think it's fine. The other two probably are, but it's not easy to see.

Sorry!

**Comment by kp52** [comment]
8d69213 looks kinda back-to-front to me - surely it's reinstating **mysql_** in place of **$modx->db->** ???
On a question of coding style, I don't see any benefit in adding curly braces around **every** variable when using double-quoted strings - they are only required in cases of ambiguity or to force evaluation of array values etc. (in which case I prefer to break out of the string and use dots). For plain **$variable** they just make it harder to read.

**Comment by kp52** [comment]
https://github.com/yama/evolution/commit/745fb681de50a2564c11742dfe356d6b2a16e0d1 meanwhile is most definiitely required, otherwise you get a syntax error (line 79)

**Comment by TimGS** [comment]
kp52: I've merged 1.1.develop into this branch. Hopefully your errors will be fixed, though I haven't tried it.

Our coding guide is at https://github.com/ClipperCMS/ClipperCMS/wiki/Coding-Guide though I don't think we have a view on double quoted strings (yet).

Note that code reformatting is discouraged unless you are changing those lines anyway. If _most_ of a file (not just a few lines) is being changed, and there is a case for reformatting the rest, then that's fine.

Reformatting causes diff to flag a line up as changed and makes code review difficult. We haven't the time to review code that hasn't in reality been functionally changed.

(That aside, I'm personally a curly brackets in double quoted strings person ;-) To me the curly brackets make them much much easier to read.)

**Comment by TimGS** [comment]
I've corrected the syntax error in another commit.

I think 8d69213 is an error as kp52 has said.

c3e7ae3 is not to be merged as it removes functionality from the DBAPI that others may be using.

The others I will merge if we can have a pull request that just highlights the lines that have been changed. Sorry my knowledge of github is not more comprehensive - I don't actually know why the whole file is being highlighted (c3e7ae3 doesn't have this issue - what did you do differently?). However we need to work out what is happening before merging. This probably needs to be made in a separate commit so I'm closing this one.

**Pull request closed without merging**
