### PR TITLE
Develop jquery tree

### PR DESCRIPTION
**Pull request by Cipa**
I am not sure if other changes will come through but maybe you can just integrate the tree ones
https://github.com/Cipa/ClipperCMS/commit/da252630415a2601c92cb1e7a601c05535ce127c

I also noticed a lot of references too mootools in setup and theme files.
Ajax Search is using moo as well. Not sure what the plan is with this one but we should remove all the mootools references. 

MM - is next for me. I will start with a fresh setup after you integrate the tree.

Thx

### CODE REVIEW

**Comment by TimGS** [comment]
I'll merge "tree to jquery"  manually later.

We cannot change AjaxSearch from mootools to jquery unless we fork it - or unless the author is willing to do it. It's not core code and we cannot stop Extra author's from using mootools (or anything else).

-- Tim.

**Comment by Cipa** [comment]
AjaxSearch: True, since jQuery is an option we can keep it as is.
Maybe we can start removing mootools from everywhere except AjaxSearch.

**Comment by TimGS** [comment]
In the core install it's in the sample site, AjaxSearch and the manager.

You are doing the manager (and I think have done most of it already).

I think Salvatore is rewriting the sample site.

Which leaves AjaxSearch, as above.

**Comment by TimGS** [comment]
Merged manually.

**Pull request closed without merging**
