### PR TITLE
Increase table width for params

### PR DESCRIPTION
**Pull request by Cipa**

### CODE REVIEW

**Comment by microcipcip** [comment]
Are you talking about plugins tab "system events"?

**Comment by TimGS** [comment]
No, though that is worth putting at width: 100%. Maybe something for the common CSS file.

The specific issue here is:
1. The plugin configuration under the 'Configuration' tab
2. Similar for TVs and snippets (see https://github.com/Cipa/ClipperCMS/commit/63393191f13130298bd80775759b7e35c7770ab4)

**Comment by microcipcip** [comment]
This one? I don't see any issue with the width.
plugin

**Comment by Cipa** [comment]
Try Plugin/QM/Configuration Tab/Plugin Configuration

**Comment by microcipcip** [comment]
I think that the issue is in the CSS in style.css:

```
form textarea {
    height: 75px;
    margin: 1px 0;
    width: 300px;
}
```

Maybe we could add (untested, making assumption that the id is always #tabProps)...

```
#tabProps form textarea {
    width: 100%;    
    max-width: 600px; 
    min-width: 300px;   
}
```

**Comment by Cipa** [comment]
But the table width is set to 300 inline
<table width="300" cellspacing="1" cellpadding="2" style="
margin-bottom:3px;background-color:#EEEEEE">

**Comment by microcipcip** [comment]
Sorry I see now, I was looking in another place. This inline styles are a nightmare. 
Maybe we should use something like this (however, as you said, width="100%" may not be a good solution for large monitor, anyway, I think we need to remove the tables in future releases if we want more freedom for the layout):

```
<table width="100%" style="margin-bottom:3px;background-color:#EEEEEE" cellpadding="2" cellspacing="1"><thead><tr><td width="30%">Parameter</td><td width="70%">Value</td></tr></thead>
```

And below...

```
<tr><td bgcolor="#FFFFFF" width="30%">'+desc+'</td><td bgcolor="#FFFFFF" width="70%">'+c+'</td></tr>
```

**Comment by TimGS** [comment]
I think width 100% is fine as long as the width of the first column is somehow limited with max-width.

Also, please no inline styles. Let's bin the old inline styles and put your CSS solution into the common CSS file.

Perhaps https://github.com/ClipperCMS/ClipperCMS/issues/323 should be closed and a more generic issue opened for checking table widths across the manager.

**Comment by microcipcip** [comment]
I don't know if it is possible to give different width to table columns without inline styles. AFAIK, it is not possible. That's why we should dump tables ASAP.

**Comment by TimGS** [comment]
Yes it is! Any element can be targetted with any CSS - easiest method is to use classnames on columns. 

Tables should only be dumped if the content is not tabular.

**Comment by microcipcip** [comment]
Yes, if we add a classname we can change that. About dumping tables, I agree that they should be used if necessary, but I don't think that the parameters sections is tabular data. Tabular data is maybe "Modules > Manage Modules" and "Security > Manager users/Web Users", or "Tools > Backup".

**Pull request closed without merging**
